server.port: 8080

secret:
  jwt:
    secret-key: pt-test-secret-key-must-be-at-least-32-bytes
    expire-time: 86400000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33306/dogether
    username: root
    password: root

  jpa.hibernate.ddl-auto: create

logging:
  config: classpath:logback/logback-local.xml
  level:
    root: info
    site.dogether: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true

